import { StyleSheet } from "react-native";

export const colors = {
  bg: "#0f172a",
  card: "#1e293b",
  border: "#334155",
  text: "#e2e8f0",
  muted: "#94a3b8",
  teal: "#14b8a6",
  tealDark: "#0f766e",
  tealBg: "rgba(20,184,166,0.15)",
  red: "#ef4444",
  redBg: "rgba(239,68,68,0.15)",
  emerald: "#34d399",
  emeraldBg: "rgba(52,211,153,0.15)",
  slate500: "#64748b",
  slate600: "#475569",
  white: "#ffffff",
  black50: "rgba(0,0,0,0.5)",
};

export const base = StyleSheet.create({
  flex1: { flex: 1 },
  bgDark: { backgroundColor: colors.bg },
  row: { flexDirection: "row" },
  rowCenter: { flexDirection: "row", alignItems: "center" },
  center: { alignItems: "center", justifyContent: "center" },
  gap2: { gap: 8 },
  gap3: { gap: 12 },
  p4: { padding: 16 },
  px4: { paddingHorizontal: 16 },
  py3: { paddingVertical: 12 },
  mb1: { marginBottom: 4 },
  mb2: { marginBottom: 8 },
  mb3: { marginBottom: 12 },
  mb4: { marginBottom: 16 },
  mb6: { marginBottom: 24 },
  mt1: { marginTop: 4 },
  mt3: { marginTop: 12 },
  mt4: { marginTop: 16 },
  mr3: { marginRight: 12 },
  card: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
  },
  input: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 14,
  },
  btnPrimary: {
    backgroundColor: colors.teal,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center" as const,
  },
  btnDisabled: {
    backgroundColor: colors.tealDark,
    opacity: 0.5,
  },
  btnOutline: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center" as const,
  },
  textXs: { fontSize: 11, color: colors.muted },
  textSm: { fontSize: 13, color: colors.muted },
  textBase: { fontSize: 15, color: colors.text },
  textLg: { fontSize: 17, color: colors.text, fontWeight: "600" as const },
  textXl: { fontSize: 20, color: colors.text, fontWeight: "700" as const },
  text3xl: { fontSize: 28, color: colors.text, fontWeight: "700" as const },
  textWhite: { color: colors.white, fontWeight: "600" as const },
  textMuted: { color: colors.muted },
  textTeal: { color: colors.teal },
  textRed: { color: colors.red },
  textCenter: { textAlign: "center" as const },
});
